# Generated by Django 6.0 on 2025-12-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('group_category', models.CharField(choices=[('Младшая', 'Младшая (2-3 года)'), ('Средняя', 'Средняя (3-4 года)'), ('Старшая', 'Старшая (4-5 лет)'), ('Подготовительная', 'Подготовительная (5-7 лет)')], max_length=20, verbose_name='Возрастная категория')),
                ('group_year', models.IntegerField(default=2024, verbose_name='Год обучения')),
                ('room_number', models.CharField(default='101', max_length=10, verbose_name='Номер кабинета')),
                ('max_capacity', models.IntegerField(default=30, verbose_name='Максимальная наполняемость')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=200, verbose_name='Название события')),
                ('event_description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('event_type', models.CharField(choices=[('holiday', 'Праздник'), ('meeting', 'Родительское собрание'), ('excursion', 'Экскурсия'), ('medical', 'Медосмотр'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип события')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, to='kindergarten.group', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_fio', models.CharField(max_length=100, verbose_name='ФИО родителя')),
                ('parent_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_fio', models.CharField(max_length=100, verbose_name='ФИО ученика')),
                ('student_birthday', models.DateField(verbose_name='Дата рождения')),
                ('student_gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('student_address', models.TextField(blank=True, verbose_name='Адрес проживания')),
                ('student_date_in', models.DateField(verbose_name='Дата поступления')),
                ('student_date_out', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_fio', models.CharField(max_length=100, verbose_name='ФИО воспитателя')),
                ('teacher_position', models.CharField(choices=[('Младший воспитатель', 'Младший воспитатель'), ('Воспитатель', 'Воспитатель'), ('Старший воспитатель', 'Старший воспитатель'), ('Заведующий', 'Заведующий'), ('Методист', 'Методист')], default='Воспитатель', max_length=50, verbose_name='Должность')),
                ('teacher_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Воспитатель',
                'verbose_name_plural': 'Воспитатели',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.teacher', verbose_name='Воспитатель'),
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Мать', 'Мать'), ('Отец', 'Отец'), ('Бабушка', 'Бабушка'), ('Дедушка', 'Дедушка'), ('Опекун', 'Опекун'), ('Другое', 'Другое')], max_length=20, verbose_name='Степень родства')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Основной контакт')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.parent', verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Связь ученик-родитель',
                'verbose_name_plural': 'Связи ученик-родитель',
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(verbose_name='Дата посещения')),
                ('status', models.BooleanField(choices=[(True, 'Присутствовал'), (False, 'Отсутствовал')], verbose_name='Статус')),
                ('reason', models.CharField(blank=True, choices=[('', 'Не указана'), ('Болезнь', 'Болезнь'), ('Отпуск', 'Отпуск родителей'), ('Семейные обстоятельства', 'Семейные обстоятельства'), ('Другое', 'Другое')], max_length=100, verbose_name='Причина отсутствия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.student', verbose_name='Ученик')),
                ('noted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.teacher', verbose_name='Отметил воспитатель')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'unique_together': {('attendance_date', 'student')},
            },
        ),
    ]
