# Generated by Django 5.2.8 on 2025-12-19 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(db_index=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(choices=[(True, 'Присутствовал'), (False, 'Отсутствовал')], db_index=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_category',
            field=models.CharField(choices=[('Младшая', 'Младшая (2-3 года)'), ('Средняя', 'Средняя (3-4 года)'), ('Старшая', 'Старшая (4-5 лет)'), ('Подготовительная', 'Подготовительная (5-7 лет)')], db_index=True, max_length=20, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_year',
            field=models.IntegerField(db_index=True, default=2024, verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_fio',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО родителя'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(db_index=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_date_in',
            field=models.DateField(db_index=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_date_out',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_fio',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО ученика'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_fio',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО воспитателя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_position',
            field=models.CharField(choices=[('Младший воспитатель', 'Младший воспитатель'), ('Воспитатель', 'Воспитатель'), ('Старший воспитатель', 'Старший воспитатель'), ('Заведующий', 'Заведующий'), ('Методист', 'Методист')], db_index=True, default='Воспитатель', max_length=50, verbose_name='Должность'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'attendance_date'], name='kindergarte_student_61438d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'status'], name='kindergarte_attenda_46f770_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status', 'attendance_date'], name='kindergarte_student_7c0fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_category', 'group_year'], name='kindergarte_group_c_e33c42_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'group_year'], name='kindergarte_teacher_470207_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['parent_fio', 'parent_number'], name='kindergarte_parent__aa396b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group', 'student_date_out'], name='kindergarte_group_i_7a1ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_fio', 'student_birthday'], name='kindergarte_student_18c899_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_fio', 'teacher_position'], name='kindergarte_teacher_f2c45c_idx'),
        ),
    ]
