# Generated by Django 5.2.8 on 2025-12-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_alter_attendance_attendance_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            # Добавляем поле user_id в таблицу parents
            sql="""
            ALTER TABLE parents 
            ADD COLUMN IF NOT EXISTS user_id INTEGER NULL 
            CONSTRAINT parents_user_id_fkey 
            REFERENCES auth_user(id) 
            ON DELETE CASCADE 
            DEFERRABLE INITIALLY DEFERRED;
            
            CREATE UNIQUE INDEX IF NOT EXISTS parents_user_id_key ON parents(user_id);
            """,
            reverse_sql="ALTER TABLE parents DROP COLUMN IF EXISTS user_id;"
        ),
        migrations.RunSQL(
            # Добавляем поле user_id в таблицу teachers
            sql="""
            ALTER TABLE teachers 
            ADD COLUMN IF NOT EXISTS user_id INTEGER NULL 
            CONSTRAINT teachers_user_id_fkey 
            REFERENCES auth_user(id) 
            ON DELETE CASCADE 
            DEFERRABLE INITIALLY DEFERRED;
            
            CREATE UNIQUE INDEX IF NOT EXISTS teachers_user_id_key ON teachers(user_id);
            """,
            reverse_sql="ALTER TABLE teachers DROP COLUMN IF EXISTS user_id;"
        ),
    ]
